theme: jekyll-theme-hacker
title: d3nhack
description: something useful... hopefully!
url: 'https//www.d3nhack.com/' # your main domain

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Dennis Nichols"
year : "2022"
